# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image for building
FROM node:18 AS builder

# Create and change to the app directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the source code to the working directory
COPY src/ ./src
COPY tsconfig.json ./

# Build the project
RUN npm run build

# Use a lighter Node.js image for the final output
FROM node:18-slim

# Set the working directory
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/dist ./dist
COPY package.json package-lock.json ./

# Install production dependencies
RUN npm install --omit=dev

# The command to run the MCP server
ENTRYPOINT ["node", "dist/index.js"]
